import type { Listing, LogEntry } from "./types";

const defaultSettings = {
  enabled: true,
  searchUrl:
    "https://www.ebay.com/sch/i.html?_nkw=Pioneer+FH-P7000MD+-junk&_sacat=0&_udlo=80&_udhi=180&LH_BIN=1",
  searchKeyword: "Pioneer FH-P7000MD",
  minPrice: 90,
  undercutAmount: 0.01,
  autoUpdateEnabled: true,
  localCheckTimeSlots: ["09:00", "17:00", "20:00"],
  priceRaiseEnabled: false,
  priceRaiseMode: "competitor_gap" as const,
  maxRaiseAmount: 5,
  ignoreConditionComparison: false,
  excludeForeignSellers: true,
  includeSellerIds: [],
  excludeSellerIds: ["MyOwnStoreJP"],
  requiredTitleKeywords: ["FH-P7000MD"],
  excludedTitleKeywords: ["junk", "parts"],
  aiJudgeEnabled: true,
};

const competitorTemplate = [
  {
    rank: 1,
    sellerId: "SellerDealsDude",
    itemPrice: 130,
    shipping: 9.99,
    total: 139.99,
    deltaFromOwn: -10.01,
    adopted: true,
  },
  {
    rank: 2,
    sellerId: "AudioPartsHub",
    itemPrice: 135,
    shipping: 7.5,
    total: 142.5,
    deltaFromOwn: -7.5,
  },
  {
    rank: 3,
    sellerId: "RetroCarAudio",
    itemPrice: 141.99,
    shipping: 4,
    total: 145.99,
    deltaFromOwn: -4.01,
  },
  {
    rank: 4,
    sellerId: "あなた",
    itemPrice: 120,
    shipping: 30,
    total: 150,
    deltaFromOwn: 0,
  },
  {
    rank: 5,
    sellerId: "DealsByDoug",
    itemPrice: 148,
    shipping: 7.25,
    total: 155.25,
    deltaFromOwn: 5.25,
  },
  {
    rank: 6,
    sellerId: "OsakaAudioExport",
    itemPrice: 151,
    shipping: 8.5,
    total: 159.5,
    deltaFromOwn: 9.5,
  },
  {
    rank: 7,
    sellerId: "VintageUnitLab",
    itemPrice: 168,
    shipping: 0,
    total: 168,
    deltaFromOwn: 18,
  },
  {
    rank: 8,
    sellerId: "CarElectronicsUS",
    itemPrice: 171.5,
    shipping: 9.99,
    total: 181.49,
    deltaFromOwn: 31.49,
  },
  {
    rank: 9,
    sellerId: "PartsResaleDepot",
    itemPrice: 189.99,
    shipping: 0,
    total: 189.99,
    deltaFromOwn: 39.99,
  },
  {
    rank: 10,
    sellerId: "TokyoTunerShop",
    itemPrice: 199,
    shipping: 14.99,
    total: 213.99,
    deltaFromOwn: 63.99,
  },
];

export const initialListings: Listing[] = [
  {
    itemId: "406875760195",
    title: "Pioneer FH-P7000MD Car Audio Used Tested",
    currentPrice: 120,
    shipping: 30,
    total: 150,
    competitorTotal: 139.99,
    suggestedPrice: 109.98,
    changePercent: -8.35,
    status: "pending",
    reason: "1回の下落率が5%以上",
    lastCheckedAt: "09:15",
    condition: "Used",
    sellerId: "MyOwnStoreJP",
    aiConfidence: 0.92,
    isOnSale: false,
    listingStatus: "Active",
    settings: defaultSettings,
    competitors: competitorTemplate,
  },
  {
    itemId: "406875760203",
    title: "Sony XAV-AX1000 Car Stereo 6.2 inch Screen",
    currentPrice: 210,
    shipping: 20,
    total: 230,
    competitorTotal: 229.95,
    suggestedPrice: 209.94,
    changePercent: -0.03,
    status: "updated",
    reason: "自動更新済み",
    lastCheckedAt: "09:10",
    condition: "Used",
    sellerId: "MyOwnStoreJP",
    aiConfidence: 0.96,
    isOnSale: false,
    listingStatus: "Active",
    settings: {
      ...defaultSettings,
      searchUrl:
        "https://www.ebay.com/sch/i.html?_nkw=Sony+XAV-AX1000&_sacat=0&_udlo=160&_udhi=260&LH_BIN=1",
      searchKeyword: "Sony XAV-AX1000",
      minPrice: 180,
      localCheckTimeSlots: ["09:00", "13:00"],
    },
    competitors: competitorTemplate.map((item) => ({
      ...item,
      itemPrice: item.itemPrice + 80,
      total: item.total == null ? null : item.total + 90,
      deltaFromOwn: item.deltaFromOwn == null ? null : item.deltaFromOwn - 0.05,
    })),
  },
  {
    itemId: "406875760287",
    title: "Alpine CDE-172BT CD Receiver Bluetooth",
    currentPrice: 95,
    shipping: 15,
    total: 110,
    competitorTotal: 109,
    suggestedPrice: 93.99,
    changePercent: -1.06,
    status: "updated",
    reason: "自動更新済み",
    lastCheckedAt: "09:08",
    condition: "Used",
    sellerId: "MyOwnStoreJP",
    aiConfidence: 0.88,
    isOnSale: false,
    listingStatus: "Active",
    settings: { ...defaultSettings, searchKeyword: "Alpine CDE-172BT", minPrice: 80 },
    competitors: competitorTemplate,
  },
  {
    itemId: "406875760342",
    title: "Kenwood KMM-BT325U Digital Media Receiver",
    currentPrice: 60,
    shipping: 10,
    total: 70,
    competitorTotal: 78.5,
    suggestedPrice: 68.49,
    changePercent: 14.15,
    status: "updated",
    reason: "自動更新済み",
    lastCheckedAt: "09:05",
    condition: "Used",
    sellerId: "MyOwnStoreJP",
    aiConfidence: 0.91,
    isOnSale: false,
    listingStatus: "Active",
    settings: { ...defaultSettings, searchKeyword: "Kenwood KMM-BT325U", minPrice: 50 },
    competitors: competitorTemplate,
  },
  {
    itemId: "406875760418",
    title: "Pioneer DEH-S31BT Car Stereo Receiver",
    currentPrice: 80,
    shipping: 10,
    total: 90,
    competitorTotal: 89.99,
    suggestedPrice: 79.98,
    changePercent: -0.03,
    status: "skipped",
    reason: "最低価格を下回る",
    lastCheckedAt: "09:02",
    condition: "Used",
    sellerId: "MyOwnStoreJP",
    aiConfidence: 0.94,
    isOnSale: false,
    listingStatus: "Active",
    settings: { ...defaultSettings, searchKeyword: "Pioneer DEH-S31BT", minPrice: 82 },
    competitors: competitorTemplate,
  },
  {
    itemId: "406875760524",
    title: "JVC KD-T720BT Double DIN Stereo",
    currentPrice: 65,
    shipping: 9.99,
    total: 74.99,
    competitorTotal: 64.99,
    suggestedPrice: 54.99,
    changePercent: -15.4,
    status: "pending",
    reason: "AI判定信頼度低",
    lastCheckedAt: "09:00",
    condition: "Used",
    sellerId: "MyOwnStoreJP",
    aiConfidence: 0.74,
    isOnSale: false,
    listingStatus: "Active",
    settings: { ...defaultSettings, searchKeyword: "JVC KD-T720BT", minPrice: 48 },
    competitors: competitorTemplate,
  },
  {
    itemId: "406875760601",
    title: "Boss BV9968B Car Stereo Receiver",
    currentPrice: 55,
    shipping: 9.99,
    total: 64.99,
    competitorTotal: 54.99,
    suggestedPrice: 44.99,
    changePercent: -18.2,
    status: "updated",
    reason: "自動更新済み",
    lastCheckedAt: "08:58",
    condition: "Used",
    sellerId: "MyOwnStoreJP",
    aiConfidence: 0.87,
    isOnSale: false,
    listingStatus: "Active",
    settings: { ...defaultSettings, searchKeyword: "Boss BV9968B", minPrice: 42 },
    competitors: competitorTemplate,
  },
  {
    itemId: "406875760687",
    title: "Clarion CZ215 CD Receiver",
    currentPrice: 45,
    shipping: 11,
    total: 56,
    competitorTotal: 54.99,
    suggestedPrice: 43.98,
    changePercent: -2.27,
    status: "pending",
    reason: "手動承認設定",
    lastCheckedAt: "08:55",
    condition: "Used",
    sellerId: "MyOwnStoreJP",
    aiConfidence: 0.81,
    isOnSale: false,
    listingStatus: "Active",
    settings: {
      ...defaultSettings,
      searchKeyword: "Clarion CZ215",
      minPrice: 35,
      autoUpdateEnabled: false,
    },
    competitors: competitorTemplate,
  },
  {
    itemId: "406875760752",
    title: "Sony XDM-17BT Media Receiver",
    currentPrice: 40,
    shipping: 10,
    total: 50,
    competitorTotal: 49.59,
    suggestedPrice: 39.58,
    changePercent: -1.05,
    status: "skipped",
    reason: "セール中商品のためスキップ",
    lastCheckedAt: "08:50",
    condition: "Used",
    sellerId: "MyOwnStoreJP",
    aiConfidence: 0.93,
    isOnSale: true,
    listingStatus: "Active",
    settings: { ...defaultSettings, searchKeyword: "Sony XDM-17BT", minPrice: 32 },
    competitors: competitorTemplate,
  },
  {
    itemId: "406875760839",
    title: "JBL GX608C 6.5 inch Component Speakers",
    currentPrice: 75,
    shipping: 15,
    total: 90,
    competitorTotal: null,
    suggestedPrice: null,
    changePercent: null,
    status: "error",
    reason: "Browse API 429 rate limit",
    lastCheckedAt: "08:45",
    condition: "Used",
    sellerId: "MyOwnStoreJP",
    aiConfidence: null,
    isOnSale: false,
    listingStatus: "Active",
    settings: { ...defaultSettings, searchKeyword: "JBL GX608C", minPrice: 60 },
    competitors: [],
  },
  {
    itemId: "406875760910",
    title: "Pioneer AVH-2400NEX Receiver Ended Listing",
    currentPrice: 180,
    shipping: 25,
    total: 205,
    competitorTotal: null,
    suggestedPrice: null,
    changePercent: null,
    status: "ended",
    reason: "出品終了",
    lastCheckedAt: "昨日",
    condition: "Used",
    sellerId: "MyOwnStoreJP",
    aiConfidence: null,
    isOnSale: false,
    listingStatus: "Ended",
    settings: { ...defaultSettings, enabled: false, searchKeyword: "Pioneer AVH-2400NEX" },
    competitors: [],
  },
];

export const initialLogs: LogEntry[] = [
  {
    id: "log-1",
    at: "2026-05-04 09:15",
    itemId: "406875760195",
    title: "Pioneer FH-P7000MD Car Audio Used Tested",
    previousPrice: 120,
    newPrice: 109.98,
    competitorTotal: 139.99,
    result: "pending_approval",
    reason: "1回の下落率が5%以上",
    aiConfidence: 0.92,
  },
  {
    id: "log-2",
    at: "2026-05-04 09:10",
    itemId: "406875760203",
    title: "Sony XAV-AX1000 Car Stereo 6.2 inch Screen",
    previousPrice: 210,
    newPrice: 209.94,
    competitorTotal: 229.95,
    result: "updated",
    reason: "自動更新済み",
    aiConfidence: 0.96,
  },
  {
    id: "log-3",
    at: "2026-05-04 09:02",
    itemId: "406875760418",
    title: "Pioneer DEH-S31BT Car Stereo Receiver",
    previousPrice: 80,
    newPrice: null,
    competitorTotal: 89.99,
    result: "skipped",
    reason: "最低価格を下回る",
    aiConfidence: 0.94,
  },
  {
    id: "log-4",
    at: "2026-05-04 08:45",
    itemId: "406875760839",
    title: "JBL GX608C 6.5 inch Component Speakers",
    previousPrice: 75,
    newPrice: null,
    competitorTotal: null,
    result: "error",
    reason: "Browse API 429 rate limit",
    aiConfidence: null,
  },
];
